Test only build/push flow
Signed-off-by: Jeroen van Erp <jeroen.vanerp@suse.com>

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -18,41 +18,41 @@ permissions:
   checks: write
 
 jobs:
-  test:
-    name: 'Tests & Linting'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Checkout'
-        uses: actions/checkout@v4
+  # test:
+  #   name: 'Tests & Linting'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 'Checkout'
+  #       uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20.x'
 
-      - name: 'Run linting'
-        run: make lint
+  #     - name: 'Run linting'
+  #       run: make lint
 
-      - name: 'Run service'
-        run: make run &
+  #     - name: 'Run service'
+  #       run: make run &
 
-      - name: 'Run tests'
-        run: |
-          sleep 5
-          make test-report
+  #     - name: 'Run tests'
+  #       run: |
+  #         sleep 5
+  #         make test-report
 
-      - name: 'Test reporting'
-        uses: phoenix-actions/test-reporting@v8
-        id: test-report
-        if: success() || failure()
-        with:
-          name: Integration Test Report
-          path: test-results.xml
-          reporter: java-junit
-          fail-on-error: false
+  #     - name: 'Test reporting'
+  #       uses: phoenix-actions/test-reporting@v8
+  #       id: test-report
+  #       if: success() || failure()
+  #       with:
+  #         name: Integration Test Report
+  #         path: test-results.xml
+  #         reporter: java-junit
+  #         fail-on-error: false
 
   build:
     name: 'Build & push image'
-    needs: test
+    # needs: test
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
     steps:
